name: dash update
on: 
  schedule:
    - cron:  '0 */28 * * *'
jobs:
  build:
    name: refresh the dashboard
    runs-on: macos-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: set_R
        uses: r-lib/actions/setup-r@master
        with:
          repository: ${{ github.repository }}
          ref: 'master'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Install pandoc 
        run: |
          brew install pandoc
          brew cask install xquartz
          brew install geos gdal  
      - name: Install CRAN packages
        run: Rscript -e "install.packages(c('devtools','usethis','plotly','mapview', 'rworldmap','leaflet','stringr','readr','tidyr','ludridate','sp','reshape2','rmarkdown', 'flexdashboard', 'dplyr', 'rnaturalearth'))" -e "install.packages(c('rgdal','rgeos'), repos='http://R-Forge.R-project.org', type='source')"
      - name: Install Github packages
        run: Rscript -e "devtools::install_github('ropensci/rnaturalearthhires',dependencies = TRUE)" -e "devtools::install_github('marovski/covid19cvdata')" 
      - name: Render the site
        run: Rscript -e "rmarkdown::render_site()"
      - name: Push updates
        if: success()
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
              git config --global user.name 'marovski'
              git config --global user.email 'cardozo27cv@gmail.com'
              git commit -am "Update cv dashboard"
              git push
          fi
