name: dash update
on: 
  schedule:
    - cron:  '*/2 * * * *'
jobs:
  build:
    name: refresh the dashboard
    runs-on: macos-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: set_R
        uses: r-lib/actions/setup-r@master
        with:
          repository: ${{ github.repository }}
          ref: 'master'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Install pandoc 
        run: |
          brew install pandoc
          brew cask install xquartz 
          #brew install pandoc-citeproc
      - name: Install CRAN packages
        run: Rscript -e "install.packages(c('devtools', 'rworldmap','leaflet','stringr','readr','tidyr','ludridate','sp','reshape2','rmarkdown', 'flexdashboard', 'dplyr'))"
      - name: Install Github packages
        run: Rscript -e "devtools::install_github('ropensci/rnaturalearthhires')" -e "devtools::install_github('marovski/covid19cvdata')" -e "devtools::install_github('ropensci/rnaturalearth')"
      - name: Render the site
        run: Rscript -e "rmarkdown::render_site()"
