name: dash update
on: 
  schedule:
    - cron:  '0 */8 * * *'
jobs:
  build:
    name: refresh the dashboard
    runs-on: macos-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: set_R
        uses: r-lib/actions/setup-r@master
        with:
          repository: ${{ github.repository }}
          ref: 'master'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Install pandoc 
        run: |
          brew install pandoc
          brew cask install xquartz 
          #brew install pandoc-citeproc
      - name: Install CRAN packages
        run: Rscript -e "install.packages(c('devtools', 'plotly','rworldmap','leaflet','stringr','readr','tidyr','ludridate','sp','reshape2','rmarkdown', 'flexdashboard', 'dplyr', 'rnaturalearth'))"
      - name: Render the site
        run: Rscript -e "rmarkdown::render_site()"
